FROM node:25-alpine AS build

WORKDIR /app

RUN npm install -g pnpm@11.0.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY frontend/package.json ./frontend/package.json
RUN pnpm install --frozen-lockfile --filter @iotables/frontend...

COPY frontend ./frontend
RUN pnpm --dir frontend build

FROM nginx:1.29-alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
